export const REQUEST_STATUS_LABELS: Record<string, string> = { received: "Ricevuta", in_review: "In valutazione", rejected: "Rifiutata", cancelled: "Annullata", quote_draft: "Preventivo in preparazione", quote_published: "Preventivo inviato", option: "In opzione", awaiting_deposit: "In attesa caparra", changes_requested: "Modifiche richieste", accepted: "Accettata", confirmed: "Confermata", preparing: "In preparazione", delivered_or_collected: "Consegnata / ritirata", returned: "Restituita", closed: "Chiusa", expired: "Scaduta" };
export const REQUEST_STATUS_DESCRIPTIONS: Record<string, string> = { received: "La richiesta è stata ricevuta ed è in attesa di verifica.", in_review: "Il gestore sta verificando i dettagli dell’evento e la logistica.", rejected: "La richiesta è stata rifiutata.", cancelled: "La richiesta è stata annullata.", quote_draft: "Il gestore sta preparando una proposta economica.", quote_published: "Il preventivo è stato inviato e può essere esaminato.", option: "Il materiale è riservato internamente fino alla scadenza dell’opzione.", awaiting_deposit: "La proposta è stata accettata: si attende la registrazione della caparra.", changes_requested: "Il cliente ha richiesto modifiche al preventivo.", accepted: "Il cliente ha accettato il preventivo.", confirmed: "L’Owner ha confermato definitivamente la richiesta.", preparing: "Il materiale è in preparazione tramite checklist operativa.", delivered_or_collected: "Il materiale è stato consegnato o ritirato ed è affidato al cliente.", returned: "Il rientro del materiale è stato registrato ed è in verifica finale.", closed: "La pratica è stata chiusa.", expired: "L’opzione è scaduta." };
export const ACTIVE_REQUEST_STATUSES = ["received", "in_review", "quote_draft", "quote_published", "option", "changes_requested", "accepted", "awaiting_deposit", "confirmed", "preparing", "delivered_or_collected", "returned"] as const;
export const ARCHIVED_REQUEST_STATUSES = ["closed", "cancelled", "rejected"] as const;
export function requestStatusLabel(status: string) { return REQUEST_STATUS_LABELS[status] ?? status; }
export function requestStatusDescription(status: string) { return REQUEST_STATUS_DESCRIPTIONS[status] ?? "Stato della pratica."; }
export function isArchivedRequestStatus(status: string) { return ARCHIVED_REQUEST_STATUSES.includes(status as (typeof ARCHIVED_REQUEST_STATUSES)[number]); }
export function requestStatusTone(status: string) {
  if (status === "closed") return "closed";
  if (["rejected", "cancelled", "expired"].includes(status)) return "critical";
  if (["confirmed", "preparing", "delivered_or_collected", "returned"].includes(status)) return "operational";
  if (["quote_published", "option", "awaiting_deposit", "changes_requested"].includes(status)) return "attention";
  return "active";
}
