import Link from "next/link";
import { saveCommunicationSettings, saveIdentitySettings, saveLogisticsSettings, saveOwnerSettings } from "@/app/area-riservata/impostazioni/actions";
export type OwnerSettings={option_duration_hours:number;operational_margin_days:number;sender_name:string;sender_email:string;owner_notification_email:string;notify_new_requests:boolean;notify_quote_responses:boolean;notify_operational_updates:boolean;pickup_enabled:boolean;delivery_enabled:boolean;pickup_address:string;pickup_instructions:string;public_name:string;public_email:string;public_phone:string;whatsapp_url:string;instagram_url:string;facebook_url:string;site_intro:string};
const Toggle=({name,label,checked}:{name:string;label:string;checked:boolean})=><label className="settings-check"><input type="checkbox" name={name} defaultChecked={checked}/><span>{label}</span></label>;
export function OwnerSettingsPanel({settings}:{settings:OwnerSettings}){return <div className="settings-stack">
<section className="settings-card settings-dark"><header><p className="detail-label">Regole operative</p><h2>Opzioni e disponibilità</h2><p>Le modifiche diventano attive appena salvi.</p></header><form action={saveOwnerSettings} className="settings-grid"><label><b>L’opzione scade dopo</b><small>Tempo massimo per cui il materiale rimane impegnato.</small><input name="optionHours" type="number" min="1" max="720" defaultValue={settings.option_duration_hours} required/></label><label><b>Lascia liberi prima e dopo</b><small>Giorni di preparazione aggiunti alle date del noleggio.</small><input name="marginDays" type="number" min="0" max="30" defaultValue={settings.operational_margin_days} required/></label><button>Salva regole</button></form></section>
<section className="settings-card"><header><p className="detail-label">Comunicazioni</p><h2>Mittente e notifiche</h2><p>Gli interruttori controllano subito gli avvisi interni inviati agli owner. I dati mittente saranno usati anche dal servizio email.</p></header><form action={saveCommunicationSettings} className="settings-grid"><label><b>Nome mittente</b><input name="senderName" defaultValue={settings.sender_name} required/></label><label><b>Email mittente</b><input name="senderEmail" type="email" defaultValue={settings.sender_email}/></label><label><b>Email owner destinataria</b><input name="ownerNotificationEmail" type="email" defaultValue={settings.owner_notification_email}/></label><fieldset><legend>Avvisi interni owner</legend><Toggle name="notifyNewRequests" label="Nuove richieste" checked={settings.notify_new_requests}/><Toggle name="notifyQuoteResponses" label="Risposte ai preventivi" checked={settings.notify_quote_responses}/></fieldset><button>Salva comunicazioni</button></form></section>
<section className="settings-card"><header><p className="detail-label">Logistica</p><h2>Ritiro e consegna</h2><p>Le modalità abilitate compaiono immediatamente nella richiesta cliente.</p></header><form action={saveLogisticsSettings} className="settings-grid"><fieldset><legend>Modalità disponibili</legend><Toggle name="pickupEnabled" label="Ritiro da parte del cliente" checked={settings.pickup_enabled}/><Toggle name="deliveryEnabled" label="Consegna da parte del gestore" checked={settings.delivery_enabled}/></fieldset><label><b>Indirizzo di ritiro</b><textarea name="pickupAddress" defaultValue={settings.pickup_address} rows={3}/></label><label className="wide"><b>Istruzioni predefinite</b><textarea name="pickupInstructions" defaultValue={settings.pickup_instructions} rows={4}/></label><button>Salva logistica</button></form></section>
<section className="settings-card"><header><p className="detail-label">Identità e aspetto</p><h2>Informazioni pubbliche</h2><p>Nome e contatti mostrati ai clienti. Il logo avrà un caricamento dedicato.</p></header><form action={saveIdentitySettings} className="settings-grid"><label><b>Nome pubblico</b><input name="publicName" defaultValue={settings.public_name} required/></label><label><b>Email pubblica</b><input name="publicEmail" type="email" defaultValue={settings.public_email}/></label><label><b>Telefono</b><input name="publicPhone" defaultValue={settings.public_phone}/></label><label><b>WhatsApp</b><input name="whatsappUrl" type="url" placeholder="https://wa.me/..." defaultValue={settings.whatsapp_url}/></label><label><b>Instagram</b><input name="instagramUrl" type="url" defaultValue={settings.instagram_url}/></label><label><b>Facebook</b><input name="facebookUrl" type="url" defaultValue={settings.facebook_url}/></label><label className="wide"><b>Testo introduttivo</b><textarea name="siteIntro" defaultValue={settings.site_intro} rows={4}/></label><button>Salva identità</button></form></section>
<section className="owner-settings-links" aria-label="Aree delle impostazioni"><Link href="/area-riservata/impostazioni/collaboratori"><span>01</span><div><h2>Collaboratori</h2><p>Invita persone, modifica il nome mostrato e abilita o sospendi l’accesso operativo.</p></div><strong>↗</strong></Link><Link href="/area-riservata/configurazione/eventi"><span>02</span><div><h2>Tipi di evento</h2><p>Gestisci le tipologie disponibili nel modulo di richiesta.</p></div><strong>↗</strong></Link><div className="settings-system"><span>03</span><div><h2>Privacy e sistema</h2><p><b>Fuso orario:</b> Europe/Rome · <b>Allegati:</b> JPG, PNG, WebP e PDF, massimo 10 MB.</p><p>Valori di sistema in sola lettura. L’informativa privacy è gestita nei documenti pubblicati.</p></div></div></section>
</div>}
