import { notFound, redirect } from "next/navigation";
import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
export const dynamic = "force-dynamic";
export default async function PracticeDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/accesso");
  const { data } = await supabase.from("requests").select("request_code,status,event_type,event_date,event_end_date,venue_name,venue_address,delivery_responsibility,pickup_responsibility,customer_notes,created_at,customer_user_id,customer_email").eq("id", id).maybeSingle(); if (!data) notFound();
  const { data: customer } = await supabase.from("profiles").select("first_name,last_name,phone").eq("user_id", data.customer_user_id).maybeSingle();
  const responsibility = (value: string) => value === "owner" ? "A carico del gestore" : "A carico del cliente";
  const customerName = customer ? customer.first_name + " " + customer.last_name : "Profilo non disponibile";
  return <main className="dashboard shell practice-detail-page"><Link href="/area-riservata/pratiche">← Torna alle pratiche</Link><div className="practice-detail-header"><div><p className="eyebrow dark">{data.request_code}</p><h1>{data.event_type}</h1><p className="practice-detail-subtitle">Cliente: {customerName}{customer?.phone ? " · " + customer.phone : ""}</p></div><strong className="status-badge">{data.status}</strong></div><div className="practice-detail-grid"><section className="practice-detail-card"><p className="detail-label">Evento</p><dl className="detail-list"><div><dt>Data inizio</dt><dd>{data.event_date}</dd></div><div><dt>Data fine</dt><dd>{data.event_end_date}</dd></div></dl></section><section className="practice-detail-card"><p className="detail-label">Location</p><h2>{data.venue_name}</h2><p>{data.venue_address}</p></section><section className="practice-detail-card"><p className="detail-label">Logistica</p><dl className="detail-list"><div><dt>Consegna</dt><dd>{responsibility(data.delivery_responsibility)}</dd></div><div><dt>Ritiro</dt><dd>{responsibility(data.pickup_responsibility)}</dd></div></dl></section>{data.customer_notes && <section className="practice-detail-card practice-detail-notes"><p className="detail-label">Note del cliente</p><p>{data.customer_notes}</p></section>}</div></main>;
}
